### ISSUE TITLE
How can I use moonnuklear with custom nk_context created in C/C++?

### ISSUE THREAD

**Issue by devildevilson** [stetre/moonnuklear#11]
Hello.

Is the library supports context transfer from (or creation at) custom C/C++ code? Is it possible?
Thanks for the library.

**Comment by stetre** [comment]
Hi, thank you.

It is not possible, currently, while it is possible the other way round (to pass to C/C++ a pointer to a context that was created in Lua).
I might add this capability, but I have to check if it is feasible.
What are the use cases?

**Comment by devildevilson** [comment]
Currently I use several hacks for debug windows and custom font backing in my app and dont want to expose this functionality in the lua. Thus I need the pointer to nk_context. It would be greatly appreciated if I could inject the pointer into your lib.

**Comment by stetre** [comment]
You may need to inject also the pointers to the fonts, then...

Injecting the context pointer should not be that difficult. I can add an alternative function to `nk.init()` that accepts a pointer to an already initialized context, encapsulated in a lua lightuserdata. Before calling that function, your C/C++ application would have to pass the pointer to Lua using the [lua_pushlightuserdata](http://www.lua.org/manual/5.3/manual.html#lua_pushlightuserdata) function of the C API. There is the issue of who is in charge to call the `nk_free()` on that pointer, but I think I can manage this easily enough.

**Comment by devildevilson** [comment]
Im using `nk_style_set_font` extensively, and the fact that moonnuklear structures isnt 1:1 nuklear.h structures means that, yes, I need some form of injecting fonts pointers. I think other things in nuklear I can use thru your library. nk_context and nk_fonts injecting covers almost completely my use-cases.

In this particular case it would be expected that the user (me) covers context destruction. No additional work for this cases is needed in my opinion. Any appropriate way for you to do this is okay.

**Comment by stetre** [comment]
Ok, then. As soon as I can I'll add a couple of experimental functions, say  `context = nk.init_from_ptr(ptr)` and `font = nk.font_from_ptr(ptr)`, both expecting lightuserdata arguments and returning the corresponding Lua objects.

The font object in MoonNuklear actually corresponds to a nk_user_font, so I think that the second function will expect a pointer to such a structure (having a nk_font, this would be the address of its field named 'handle').

**Comment by devildevilson** [comment]
Great.
Thanks for the fast reply.

**Comment by stetre** [comment]
I've implemented the functions but not tested them. The backend used in the examples won't work here, so you'll have to either adapt it, or write your own.

Good luck, and let me know if it works.

**Comment by devildevilson** [comment]
Few fast tests shows that the context works perfectly. I have several issues with fonts, probably my bad, But I can check it only at the morning.

**Comment by stetre** [comment]
I didn't mention that in the end I made the `nk.font_from_ptr()` accept a pointer to a nk_font (not to a nk_user_font). Maybe the issues are caused by this.

**Comment by devildevilson** [comment]
Everything works fine, good job.

![briliant_lua3](https://user-images.githubusercontent.com/50243012/92446751-f5509280-f1be-11ea-9ff8-8d5390b54189.png)
(font size too small, haha)
