### ISSUE TITLE
Known issue with nk.init_from_ptr

### ISSUE THREAD

**Issue by devildevilson** [stetre/moonnuklear#12]
Hello again
Upon further testing the `nk.init_from_ptr` function, some issue has been found. 
The _nuklear.h_ file in **moonnuklear** and the file in user project may have been compiled with different defines, this may lead to "SEGFAULT invalid address", for example, when the user called the `nk.edit_string` function.
It would be appreciate to add some note about it (and about the default defines) in the docs.
Secondly, the solution could be something like: make the public header with the defines (like _moonnuklear/include/moonnuklear.h_), and strongly recommend the users, that may want to use `nk.init_from_ptr`, to include the public header to their project.

**Comment by stetre** [comment]
This is not completely unexpected. I was wary of issues arising from not being MoonNuklear a binding to a shared library.

I will add these notes to the docs ASAP. Thank you for the feedback.

**Comment by devildevilson** [comment]
Ok. Thank you
