### ISSUE TITLE
image.c has a buffer overrun

### ISSUE THREAD

**Issue by awsdert** [stetre/moonnuklear#14]
You have this:
```
static int Image_info(lua_State *L)
    {
    ud_t *ud;
    nk_rect_t r;
    nk_image_t *image = checkimage(L, 1, &ud);
    if(IsImageId(ud))
        lua_pushlightuserdata(L, image->handle.ptr);
    else
        lua_pushinteger(L, image->handle.id);
    if(!IsSubImage(ud))
        return 1;
    lua_pushinteger(L, image->w);
    lua_pushinteger(L, image->h);
    r.x = image->region[0];
    r.y = image->region[2];
    r.w = image->region[3];
    r.h = image->region[4];
    pushrect(L, &r);
    return 1;
    }
```
I assumed you meant this:
```
static int Image_info(lua_State *L)
    {
    ud_t *ud;
    nk_rect_t r;
    nk_image_t *image = checkimage(L, 1, &ud);
    if(IsImageId(ud))
        lua_pushlightuserdata(L, image->handle.ptr);
    else
        lua_pushinteger(L, image->handle.id);
    if(!IsSubImage(ud))
        return 1;
    lua_pushinteger(L, image->w);
    lua_pushinteger(L, image->h);
    r.x = image->region[0];
    r.y = image->region[1];
    r.w = image->region[2];
    r.h = image->region[3];
    pushrect(L, &r);
    return 1;
    }
```
I changed it my end thinking that was what was causing the library to fail to load during runtime, after a few more edits to how I handled the errors given to me this is the most prominent error I expect caused my problem:
```
~/lib/moonnuklear.so had error:  undefined symbol: lua_newuserdata
```
Should I attribute that to a bug in moonnuklear or a bug in my own code:
```
function _RequireLib(dir,name,report_attempts,error_on_failure)
	local paths, p, v, ret, err, all
	paths = { name, name .. ".so" }
	all = {}
	for p, v in pairs(paths) do
		if not ret then
			local path
			if dir then
				path = dir .. "/" .. v
			else
				path = v
			end
			if report_attempts then
				print("Trying " .. path)
			end
			paths[p] = path
			ret, err = loadlib(path,'luaopen_' .. name)
			all[p] = err
		end
	end
	
	if ret then
		return pcall( ret ), err, ret
	end
	
	if error_on_failure then
		dump_lua_stack()
		path = debug.traceback()
		for p, v in pairs(all) do
			path = path .. "\n " .. v
		end
		path = "Failed to load library " .. name .. "\n" ..  path
		print( path )
		error( path )
	end
	
	return nil, err, ret
end
```
...actually this might be the same error the normal require() encountered but failed to report to me

**Comment by stetre** [comment]
I fixed the buffer overrun error, thank you for noticing it.

As for the undefined symbol, I don't think it is related. Are you using the default Makefile or a custom one?

**Comment by awsdert** [comment]
default, I just cd into the dir and run make

**Comment by awsdert** [comment]
Just realised, I've using lua 5.4 as I couldn't get lua 5.3 going, maybe that's the cause

**Comment by stetre** [comment]
Did you pass LUAVER=5.4 ? See https://github.com/stetre/moonlibs#lua-version

**Comment by awsdert** [comment]
No I hadn't will try later, in meantime there's another bug that keeps cropping up:
```
nuklear/nuklear.h:27363:16: warning: ‘num_len’ may be used uninitialized in this function [-Wmaybe-uninitialized]
```
I've now changed the declaration code to set it to 0 instead of just declaring the variable, I know this isn't from your code but do you think it would've caused any problems?

**Comment by awsdert** [comment]
Yeah that seemed to resolve it, although your info says "LUA_VER" whereas I had to use "LUAVER"

**Comment by stetre** [comment]
> Yeah that seemed to resolve it, although your info says "LUA_VER" whereas I had to use "LUAVER"

Are you sure? Where?

**Comment by awsdert** [comment]
I simply passed it on via
```
make LUAVER=$(LUAVER)
```
