### ISSUE TITLE
Backend not found?

### ISSUE THREAD

**Issue by Frityet** [stetre/moonnuklear#15]
Trying to run any example after compiling gives this error

```yaml
lua: examples/demo.lua:5: module 'backend' not found:
	no field package.preload['backend']
	no file '/usr/local/share/lua/5.4/backend.lua'
	no file '/usr/local/share/lua/5.4/backend/init.lua'
	no file '/usr/local/lib/lua/5.4/backend.lua'
	no file '/usr/local/lib/lua/5.4/backend/init.lua'
	no file './backend.lua'
	no file './backend/init.lua'
	no file '/usr/local/lib/lua/5.4/backend.so'
	no file '/usr/local/lib/lua/5.4/loadall.so'
	no file './backend.so'
stack traceback:
	[C]: in function 'require'
	examples/demo.lua:5: in main chunk
	[C]: in ?
``` anyone got a clue?

**Comment by stetre** [comment]
Enter the examples/ directory and run the demo from there.

The backend.lua script is in that directory, so if you run demo.lua from the parent directory, the Lua interpreter won't find it (as you can see from the paths listed in the error message, it doesn't search for ./examples/backend.lua ).

**Comment by Frityet** [comment]
> Enter the examples/ directory and run the demo from there.
> 
> The backend.lua script is in that directory, so if you run demo.lua from the parent directory, the Lua interpreter won't find it (as you can see from the paths listed in the error message, it doesn't search for ./examples/backend.lua ).

Thank you!
