### ISSUE TITLE
Link/Compile Time error

### ISSUE THREAD

**Issue by awsdert** [stetre/moonnuklear#4]
So I've been reworking the makefile a little so that a more portable library is spat out (ie doesn't need to be installed) and since lua doesn't compile a shared library of any kind I had to link statically for it, the problem however is that the version apparently doesn't match up, here's my output:
```
make
cd moonnuklear && git fetch
cd lua && git fetch
cd lua && make
make[1]: Entering directory 'lua'
make[1]: 'all' is up to date.
make[1]: Leaving directory 'lua'
cd moonnuklear && make LUA_DIR=../../lua
make[1]: Entering directory 'moonnuklear'
make[2]: Entering directory 'moonnuklear/src'
rm -f *.so *.dll *.o *.err *.map *.S *~ *.log *.dylib
rm -f moonnuklear.symbols
cc -O2 -Wall -Wextra -Wpedantic -std=gnu99 -DLUAVER=5.3 -fpic -DLINUX -I./nuklear -I'../../lua'   -c -o enums.o enums.c
cc -O2 -Wall -Wextra -Wpedantic -std=gnu99 -DLUAVER=5.3 -fpic -DLINUX -I./nuklear -I'../../lua'   -c -o image.o image.c
cc -O2 -Wall -Wextra -Wpedantic -std=gnu99 -DLUAVER=5.3 -fpic -DLINUX -I./nuklear -I'../../lua'   -c -o panel.o panel.c
cc -O2 -Wall -Wextra -Wpedantic -std=gnu99 -DLUAVER=5.3 -fpic -DLINUX -I./nuklear -I'../../lua'   -c -o flags.o flags.c
cc -O2 -Wall -Wextra -Wpedantic -std=gnu99 -DLUAVER=5.3 -fpic -DLINUX -I./nuklear -I'../../lua'   -c -o nuklear.o nuklear.c
cc -O2 -Wall -Wextra -Wpedantic -std=gnu99 -DLUAVER=5.3 -fpic -DLINUX -I./nuklear -I'../../lua'   -c -o layout.o layout.c
cc -O2 -Wall -Wextra -Wpedantic -std=gnu99 -DLUAVER=5.3 -fpic -DLINUX -I./nuklear -I'../../lua'   -c -o window.o window.c
cc -O2 -Wall -Wextra -Wpedantic -std=gnu99 -DLUAVER=5.3 -fpic -DLINUX -I./nuklear -I'../../lua'   -c -o cursor.o cursor.c
cc -O2 -Wall -Wextra -Wpedantic -std=gnu99 -DLUAVER=5.3 -fpic -DLINUX -I./nuklear -I'../../lua'   -c -o objects.o objects.c
cc -O2 -Wall -Wextra -Wpedantic -std=gnu99 -DLUAVER=5.3 -fpic -DLINUX -I./nuklear -I'../../lua'   -c -o atlas.o atlas.c
cc -O2 -Wall -Wextra -Wpedantic -std=gnu99 -DLUAVER=5.3 -fpic -DLINUX -I./nuklear -I'../../lua'   -c -o versions.o versions.c
cc -O2 -Wall -Wextra -Wpedantic -std=gnu99 -DLUAVER=5.3 -fpic -DLINUX -I./nuklear -I'../../lua'   -c -o utils.o utils.c
cc -O2 -Wall -Wextra -Wpedantic -std=gnu99 -DLUAVER=5.3 -fpic -DLINUX -I./nuklear -I'../../lua'   -c -o context.o context.c
cc -O2 -Wall -Wextra -Wpedantic -std=gnu99 -DLUAVER=5.3 -fpic -DLINUX -I./nuklear -I'../../lua'   -c -o main.o main.c
cc -O2 -Wall -Wextra -Wpedantic -std=gnu99 -DLUAVER=5.3 -fpic -DLINUX -I./nuklear -I'../../lua'   -c -o edit.o edit.c
cc -O2 -Wall -Wextra -Wpedantic -std=gnu99 -DLUAVER=5.3 -fpic -DLINUX -I./nuklear -I'../../lua'   -c -o buffer.o buffer.c
cc -O2 -Wall -Wextra -Wpedantic -std=gnu99 -DLUAVER=5.3 -fpic -DLINUX -I./nuklear -I'../../lua'   -c -o font.o font.c
cc -O2 -Wall -Wextra -Wpedantic -std=gnu99 -DLUAVER=5.3 -fpic -DLINUX -I./nuklear -I'../../lua'   -c -o widgets.o widgets.c
cc -O2 -Wall -Wextra -Wpedantic -std=gnu99 -DLUAVER=5.3 -fpic -DLINUX -I./nuklear -I'../../lua'   -c -o input.o input.c
cc -O2 -Wall -Wextra -Wpedantic -std=gnu99 -DLUAVER=5.3 -fpic -DLINUX -I./nuklear -I'../../lua'   -c -o tracing.o tracing.c
cc -O2 -Wall -Wextra -Wpedantic -std=gnu99 -DLUAVER=5.3 -fpic -DLINUX -I./nuklear -I'../../lua'   -c -o canvas.o canvas.c
cc -O2 -Wall -Wextra -Wpedantic -std=gnu99 -DLUAVER=5.3 -fpic -DLINUX -I./nuklear -I'../../lua'   -c -o structs.o structs.c
cc -O2 -Wall -Wextra -Wpedantic -std=gnu99 -DLUAVER=5.3 -fpic -DLINUX -I./nuklear -I'../../lua'   -c -o udata.o udata.c
cc -O2 -Wall -Wextra -Wpedantic -std=gnu99 -DLUAVER=5.3 -fpic -DLINUX -I./nuklear -I'../../lua'   -c -o style.o style.c
cc -shared -o libmoonnuklear.so enums.o image.o panel.o flags.o nuklear.o layout.o window.o cursor.o objects.o atlas.o versions.o utils.o context.o main.o edit.o buffer.o font.o widgets.o input.o tracing.o canvas.o structs.o udata.o style.o -L'../../lua' -l:lua
/usr/bin/ld: ../../lua/lua: stdin: invalid version 3 (max 0)
/usr/bin/ld: ../../lua/lua: error adding symbols: bad value
collect2: error: ld returned 1 exit status
make[2]: Leaving directory 'moonnuklear/src'
make[2]: *** [Makefile:156: moonnuklear] Error 1
make[1]: Leaving directory 'moonnuklear'
make[1]: *** [Makefile:5: build] Error 2
make: *** [makefile:39: moonnuklear/src/libmoonnuklear.so] Error 2
Compilation failed.
```
Any ideas on how I can resolve this? (Btw the reason I need this to not install is cause I'm making a cheat trainer and it would be poor taste to force an installation)

**Comment by stetre** [comment]
Hi. I'm not sure I understood what you want to achieve. Are you trying to bundle lua with moonnuklear? Or do you want to avoid installing moonnuklear itself?

**Comment by awsdert** [comment]
Trying to avoid installing moonnuklear, I making a cheat app and my usual goto (IUP from Tegraf) is not compiling on manjaro (which I'm on) and neither does CEGUI (also MIT License) so I started looking at libs that used opengl.
For now I've given up on moonnuklear and various other libs I've looked at and gone with freeglut which was preinstalled

**Comment by stetre** [comment]
If the problem is that you can't (or don't want to) install it as root, you can make a local install by overriding the PREFIX variable used in the makefile, do the same for the other libraries used to implement the backend (MoonGL and MoonGLFW) and then set the LUA_PATH and LUA_CPATH so that Lua can find them.

Right now I'm a bit busy, but I'll write a short note on how to do it ASAP.

**Comment by stetre** [comment]
I've added to the MoonLibs README a section with instructions on [how to install to a custom location](https://github.com/stetre/moonlibs#install-location). Hope that helps.

EDIT: Formatting.

**Comment by awsdert** [comment]
Thanks, I only just noticed you're response via my e-mail (don't often check), quick question, how did you plugin the callback functions to be relative to the window created/retrieved, I've been struggling with that for a while now and have not been able to get the functions to execute after duplication, currently I think I'm just the position of the source bytes wrong, I'll look at your api more while I wait since I only looked for stuff that I could use in place of IUP which for some reason is not installing/compiling

**Comment by stetre** [comment]
Do you mean the GLFW callbacks? If so, those are relative to the GLFW window (not to be confused with Nuklear 'window' objects), and you pass to the 'set' functions the handle returned by `glfw.create_window()`.

**Comment by awsdert** [comment]
No the glut callbacks, like glutDisplayFunc()

**Comment by stetre** [comment]
I did not use glut in this project. The only backend I implemented - the one used in the examples - uses GLFW for window creation and input handling (via the MoonGLFW bindings). Are you implementing an alternative backend with GLUT instead? 

However, if I recall correctly, glutDisplayFunc() sets the callback for the current window, so if you are duplicating a window you should call the function again after duplication, as soon as the new window is 'current'.

BTW, if you are using the MoonGLUT bindings, please keep in mind that I'm not maintaining them anymore and consider using MoonGLFW, instead, which is a much better alternative.
