### ISSUE TITLE
Need a little help getting to grips with the tree calls

### ISSUE THREAD

**Issue by awsdert** [stetre/moonnuklear#7]
So far I managed this:
```
return function(gui,ctx,prv)
	local ok, selected
	if nk.tree_push( ctx, nk.TREE_NODE,
		"Noticed Processes", "no", gui.idc ) then
		gui.idc = gui.idc + 1
		local glance = class_proc_glance()
		if type(glance) == "userdata" then
			local notice = glance:init("gasp")
			while notice do
				ok, selected = tree_element_push(
					ctx, nk.TREE_NODE,
					"" .. notice.id .. notice.name,
					"0", gui.idc)
				if ok then
					gui.idc = gui.idc + 1
					notice = glance:next()
				else break end
			end
			glance:term()
		end
	end
	nk.tree_pop()
	return gui
end
```
But that collapsestates one I need a bit of help understanding since I keep getting it wrong

**Comment by awsdert** [comment]
Never mind, found it, needed to use nk.MAXIMIZED

**Comment by awsdert** [comment]
Rather than create a new issue for a related subject I'll just tack it on this one since peops viewing this thread will probably encounter the same issue
Managed to resolve some bugs my end regarding adding a new class, used the class only to find nuklear complaing I haven't added the tree despite moving the nk.tree_pop() call inside the if statement used for pushing in the tree in the 1st place, mind taking a look and seeing if can spot the problem?
```
return function(gui,ctx,prv)
	local font = get_font(gui)
	local ok, selected
	local text = "Noticed Processes"
	local glance = class_proc_glance.new()
	if glance then
		local notice = glance:init("gasp")
		if notice then
			nk.layout_row_dynamic(ctx, pad_height(font,text), 1)
			if nk.tree_push( ctx, nk.TREE_NODE,
			text, nk.MAXIMIZED, gui.idc ) then
				gui.idc = gui.idc + 1
				while notice do
					text = "" .. notice.entryId  .. " " .. notice.name
					ok, gui.selected[gui.idc] = nk.tree_element_push(
						ctx, nk.TREE_NODE, text, nk.MAXIMIZED,
						(gui.selected[gui.idc] or false), gui.idc )
					if ok then
						gui.idc = gui.idc + 1
						notice = glance:next()
					else break end
				end
				nk.tree_pop(ctx)
			end
		end
		glance:term()
	end
	nk.layout_row_dynamic(ctx, pad_height(font,text), 1 )
	if nk.button(ctx, nil, "Done") then
		 gui.which = prv
	end
	return gui
end
```

**Comment by stetre** [comment]
Can you post also the error message?

**Comment by awsdert** [comment]
> NK_ASSERT failed: nuklear/nuklear.h line 16125
And at that line is this:
```
 /* helper to make sure you have a 'nk_tree_push' for every 'nk_tree_pop' */
 NK_ASSERT(!layout->row.tree_depth);
```

**Comment by stetre** [comment]
The lua part of the message could have been of help, also. However, in your code I don't see the `nk.tree_element_pop()` corresponding to the `nk.tree_element_push()` call. That should be the cause.

**Comment by awsdert** [comment]
Thing is lua didn't give anything despite me having set the atpanic call, must need something else to catch that, anyways I didn't even realise I missed the nk.tree_element_pop() call, I'll give that a try now

**Comment by awsdert** [comment]
Yep that resolved that, although the window immediately shuts on me afterwards, looking for the cause now, so far I only stuck the call in the if ok statement, might need to move it to another loop

**Comment by awsdert** [comment]
Nope that made it shut without me getting to see the list for even a second

**Comment by awsdert** [comment]
Tried nk.MINIMIZED in the element push call and that kept the window open however I then noticed an issue with the tree itself, the way I had initially intended was for all processes to show in a list format however the result was every subsequent element became a child of the previous element, any ideas?

**Comment by stetre** [comment]
This last issue should be the consequence of nested `tree_element_push()` calls. The correct position for the `tree_element_pop()` call is at the end of the `if ok then` branch.

**Comment by awsdert** [comment]
Erm if I'm not mistaken that's what I already have:
```
if ok then
	gui.idc = gui.idc + 1
	notice = glance:next()
	nk.tree_element_pop(ctx)
else break end
```

**Comment by stetre** [comment]
Are you sure? I just tried modifying the tree in the overview.lua example to add a few non-nested tree elements, and they indeed are displayed at the same level, as a list.

**Comment by awsdert** [comment]
No it only looks like it, when nk.MINIMIZED is used each individual node has to be clicked to show the next

**Edit:** Just noticed your mention of overview.lua, not an intuitive name for tree example but I'll look at it anyways since I've only just found out about it

**Comment by awsdert** [comment]
I think I got it but window closes on me before I have a chance to take in what I see, here's what I have (don't mind the workarounds for my own bugs)
```
return function(gui,ctx,prv)
	local font = get_font(gui)
	local ok, selected
	local text = "Noticed Processes"
	local glance = proc_locate_name("gasp")
	if glance then
		nk.layout_row_dynamic(ctx, pad_height(font,text), 1)
		if nk.tree_push( ctx, nk.TREE_NODE,
		text, nk.MAXIMIZED, gui.idc ) then
			gui.idc = gui.idc + 1
			nk.layout_row_dynamic(ctx, pad_height(font,text), 1)
			for i,notice in pairs(glance) do
				print("type(" .. i .. ") = " .. type(notice))
				if type(notice) == "table" then
					for j,v in pairs(notice) do
						print("\ttype(" .. j .. ") = " .. type(v))
					end
					text = "" .. (notice.entryId or "?")  ..
						" " .. (notice.name or "(nil)")
				else
					text = "(nil)"
				end
				gui.selected[gui.idc] = nk.selectable(
					ctx, nil, text, nk.TEXT_LEFT,
					(gui.selected[gui.idc] or false) )
					gui.idc = gui.idc + 1
			end
		end
		nk.tree_pop(ctx)
	end
	nk.layout_row_dynamic(ctx, pad_height(font,text), 1 )
	if nk.button(ctx, nil, "Done") then
		 gui.which = prv
	end
	return gui
end
```
Any ideas on why the window suddenly shuts on me?

**Comment by stetre** [comment]
The name comes from the fact that it is an overview of Nuklear features (trees among other). It is part of the demo.lua example, a port of the original Nuklear demo. If you look for examples for a particular widget, you'll likely find one in that demo.

EDIT: Just saw your last post now. I'll look at it tomorrow morning (I'm a bit busy this evening).

**Comment by awsdert** [comment]
Fair enough, at least I managed to fix the bug those workarounds were in for, since that code above is now more complex than needed I'll post the updated one here:
```
return function(gui,ctx,prv)
	local font = get_font(gui)
	local ok, selected
	local text = "Noticed Processes"
	local glance = proc_locate_name("gasp")
	if glance and #glance > 0 then
		nk.layout_row_dynamic(ctx, pad_height(font,text), 1)
		if nk.tree_push( ctx, nk.TREE_NODE,
		text, nk.MAXIMIZED, gui.idc ) then
			gui.idc = gui.idc + 1
			nk.layout_row_dynamic(ctx, pad_height(font,text), 1)
			for i,notice in pairs(glance) do
				print("type(" .. i .. ") = " .. type(notice))
				text = "" .. notice.entryId .. " " .. notice.name
				gui.selected[gui.idc] = nk.selectable(
					ctx, nil, text, nk.TEXT_LEFT,
					(gui.selected[gui.idc] or false) )
				gui.idc = gui.idc + 1
			end
		end
		nk.tree_pop(ctx)
	end
	nk.layout_row_dynamic(ctx, pad_height(font,text), 1 )
	if nk.button(ctx, nil, "Done") then
		 gui.which = prv
	end
	return gui
end
```

**Comment by awsdert** [comment]
Alright after a lot of commenting and un-commenting it seems the root of the disappearing window issue is the list I return in proc_locate_name(), since you're more experienced in the lua C API mind taking a look at the function?
```
int lua_proc_locate_name( lua_State *L ) {
	int ret = EXIT_SUCCESS, underId = luaL_optinteger(L,2,0);
	char const *name = luaL_checkstring(L,1);
	nodes_t nodes = {0};
	proc_notice_t *notice;
	node_t i;
	
	name = lua_tostring(L,1);
	notice = proc_locate_name( &ret, name, &nodes, underId );
	lua_createtable( L, nodes.count, 0 );
	for ( i = 0; i < nodes.count; ++i ) {
		lua_pushinteger(L,i+1);
		lua_createtable( L, 0, 5 );
		push_branch_bool( L, "self", notice->self );
		push_branch_int( L, "entryId", notice->entryId );
		push_branch_int( L, "ownerId", notice->ownerId );
		push_branch_str( L, "name", (char*)(notice->name.block) );
		push_branch_str( L, "cmdl", (char*)(notice->cmdl.block) );
		lua_settable(L,-3);
		proc_notice_zero( notice );
		++notice;
	}
	free_nodes( proc_notice_t, &ret, &nodes );
	return 1;
}
```
And for clarity:
```
void push_branch_str( lua_State *L, char const *key, char *val ) {
	lua_pushstring(L,key);
	lua_pushstring(L,val);
	lua_settable(L,-3);
}

void push_branch_int( lua_State *L, char const *key, int val ) {
	lua_pushstring(L,key);
	lua_pushinteger(L,val);
	lua_settable(L,-3);
}

void push_branch_bool( lua_State *L, char const *key, bool val ) {
	lua_pushstring(L,key);
	lua_pushboolean(L,val);
	lua_settable(L,-3);
}
```

**Edit:** Forgot to mention that proc_notice_zero() free's the memory allocated for name & cmdl, would that make a difference?

**Comment by stetre** [comment]
No, that's ok (see http://www.lua.org/manual/5.3/manual.html#lua_pushstring ).

You don't need this call: `name = lua_tostring(L,1);` since you already called `char const *name = luaL_checkstring(L,1);`.

Other than that, at a glance, I don't see errors. Have you tried printing the returned value from Lua to see if it matches your expectations?

**Comment by awsdert** [comment]
Whoopsie, that tostring is just a left over from when I took some advice from the lua mailing list.
As for the printing, do you mean the individual values I pushed in? Yeah, that's what that whole work-around thing was about a few posts ago, I was not getting the expected tables in the list at that time but now I am and while the window is still open I can see they come out correctly, just need the window to stay open, since lua doesn't report anything I'm assuming an exit call is occuring due to an unexpected situation, btw I have already uploaded the changes, here's think link if you feel like looking in other spots:
https://github.com/awsdert/gasp/tree/6db7aca32c716de1ed2650116055c2bca28333cc
If you do go looking then the one to start with would probably be the draw_all() function in gasp.lua

**Comment by awsdert** [comment]
Found the cause, turns out some random /proc/pid/status file/s had incomplete information and/or ended with an unexpected \0 character resulting in a hidden segfault (which I found after I eventually thought to run the debugger, gonna try with nk.tree_element_push one last time just to make sure I got a grip on how to use it correctly (wouldn't wanna re-open this issue week/s later when I'm using the interface for the "memory records" as Cheat Engine puts it)

**Comment by awsdert** [comment]
Yeah it's working fine now, for the reference of peops visiting this thread later here's the specific
github tree where the code is still small enough to traverse and see an example of configuring font from a specific section and using lists/trees in the same app, to remember the change one just has to overwrite the cfg.lua from in app with the new value/s (well I didn't actually implement that but you can figure that out without my or stetre's help)
