### ISSUE TITLE
Docs don't interlink properly

### ISSUE THREAD

**Issue by awsdert** [stetre/moonnuklear#9]
Try clicking on the link for any struct and you'll see what I mean, once I modify the uri in my address bar to use structs.adoc instead of whatever doc I was on then I get the relevant struct scrolled into view

**Comment by stetre** [comment]
I'm not sure I understood the problem. Are you talking about the reference manual at this link?
https://stetre.github.io/moonnuklear/doc/index.html

**Comment by awsdert** [comment]
No, the *.adoc files, visted them on github via web browser and whenever I click on something not in the same doc it just ignores it essentially

**Comment by stetre** [comment]
The *.adoc files are the sources from which the html doc is generated. They are not supposed to be browsed.

**Comment by awsdert** [comment]
Oh, did not realise, btw I didn't find anything for the _modify parameter in this one:
https://github.com/stetre/moonnuklear/blob/master/doc/widgets.adoc#modify
I'll take a look at index now but I don't hold much hope if even the structs.adoc doesn't have it

*Edit* I meant under nk.progress there

**Comment by stetre** [comment]
There's a typo, an extra underscore. I'll fix it immediately.

**Comment by stetre** [comment]
Fixed. The 'modify' argument is an enum. If you click on it in the html doc (`doc/index.html`) it should correctly bring you to its definition, in the 'Enums' section of the same doc.

**Comment by awsdert** [comment]
Thank you :)
